# Generated by Django 5.0.2 on 2025-02-01 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0005_resume_job_matches'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='resume_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
