# Generated by Django 5.0.2 on 2025-02-01 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0006_resume_resume_content_resume_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/thumbnails/'),
        ),
    ]
