services:
  web:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend/:/usr/src/backend/
    ports:
      - "8001:8000"  # Change the exposed port
    env_file:
      - ./.env.dev
    depends_on:
      - airesume_db
  airesume_db:
    image: postgres:15
    volumes:
      - airesume_postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_DB=airesumeinsights

volumes:
  airesume_postgres_data:
